"""remove user column in room

Revision ID: 1e8af7867573
Revises: 4e25d5992d41
Create Date: 2020-11-08 19:11:28.999399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8af7867573'
down_revision = '4e25d5992d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
