"""changed column name to participants

Revision ID: 2854c11f91a1
Revises: b30876105468
Create Date: 2020-11-08 20:36:45.566310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2854c11f91a1'
down_revision = 'b30876105468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('participants', sa.String(length=5000), nullable=True))
    op.drop_column('room', 'subscribers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('subscribers', sa.BLOB(), nullable=True))
    op.drop_column('room', 'participants')
    # ### end Alembic commands ###
