"""changed to REAL column of personal message

Revision ID: 75973368139a
Revises: 
Create Date: 2020-11-22 10:57:59.146925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75973368139a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_message', 'created_date',
               existing_type=mysql.FLOAT(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('personal_message', 'modified_date',
               existing_type=mysql.FLOAT(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('room_message', 'created_date',
               existing_type=mysql.FLOAT(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('room_message', 'modified_date',
               existing_type=mysql.FLOAT(),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room_message', 'modified_date',
               existing_type=sa.REAL(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('room_message', 'created_date',
               existing_type=sa.REAL(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('personal_message', 'modified_date',
               existing_type=sa.REAL(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('personal_message', 'created_date',
               existing_type=sa.REAL(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###
