"""removed index

Revision ID: 775dddb9a098
Revises: fa7326ad7d69
Create Date: 2020-11-12 12:30:24.590045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775dddb9a098'
down_revision = 'fa7326ad7d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_id', table_name='room')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_constraint('user_room_ibfk_1', 'user_room', type_='foreignkey')
    op.create_foreign_key(None, 'user_room', 'room', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_room', type_='foreignkey')
    op.create_foreign_key('user_room_ibfk_1', 'user_room', 'user', ['room_id'], ['id'])
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_room_id', 'room', ['id'], unique=False)
    # ### end Alembic commands ###
