"""Create Tables

Revision ID: 777c680a267e
Revises: 
Create Date: 2021-01-03 20:10:52.303761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '777c680a267e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('personal_message', 'created_date',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('personal_message', 'modified_date',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('room_message', 'created_date',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('room_message', 'modified_date',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('user', sa.Column('full_name', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'profile', ['profile_id'], ['id'])
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('user', sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'profile_id')
    op.drop_column('user', 'full_name')
    op.alter_column('room_message', 'modified_date',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('room_message', 'created_date',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('personal_message', 'modified_date',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('personal_message', 'created_date',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.drop_table('sheet')
    op.drop_table('profile')
    # ### end Alembic commands ###
