"""changed to func.current_tiemstamp from func.now() on base message

Revision ID: 798dc6a4b85b
Revises: cf950a6f1703
Create Date: 2020-11-22 22:29:00.388314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798dc6a4b85b'
down_revision = 'cf950a6f1703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
