"""added a column admin to room table

Revision ID: 8cf0dfc962cf
Revises: 50dca43cd227
Create Date: 2020-11-09 15:24:04.208262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf0dfc962cf'
down_revision = '50dca43cd227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('admin', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'admin')
    # ### end Alembic commands ###
