"""changed to REAL column server datetime of base message

Revision ID: abcfe29f88a4
Revises: 75973368139a
Create Date: 2020-11-22 22:00:49.125777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abcfe29f88a4'
down_revision = '75973368139a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_message', 'created_date',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('personal_message', 'modified_date',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('room_message', 'created_date',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('room_message', 'modified_date',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room_message', 'modified_date',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('room_message', 'created_date',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('personal_message', 'modified_date',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('personal_message', 'created_date',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    # ### end Alembic commands ###
