"""modified subscribers to pickletype

Revision ID: b30876105468
Revises: ee3dffe1625c
Create Date: 2020-11-08 20:12:33.113680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30876105468'
down_revision = 'ee3dffe1625c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
