"""add column is_social_account

Revision ID: b33d3088b89b
Revises: 88b1e3dfd0d1
Create Date: 2020-11-08 14:57:20.582118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33d3088b89b'
down_revision = '88b1e3dfd0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_social_account', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_social_account')
    # ### end Alembic commands ###
