"""added user column to room

Revision ID: bab0d5b94c75
Revises: 1e8af7867573
Create Date: 2020-11-08 19:16:58.318632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab0d5b94c75'
down_revision = '1e8af7867573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
