"""changed to server_default to default on base message

Revision ID: cf950a6f1703
Revises: abcfe29f88a4
Create Date: 2020-11-22 22:22:19.894289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf950a6f1703'
down_revision = 'abcfe29f88a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
