"""imposed many to many relation

Revision ID: e743acc60874
Revises: 2854c11f91a1
Create Date: 2020-11-09 15:15:38.574537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e743acc60874'
down_revision = '2854c11f91a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_constraint('room_ibfk_1', 'room', type_='foreignkey')
    op.drop_column('room', 'participants')
    op.drop_column('room', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('participants', mysql.VARCHAR(length=5000), nullable=True))
    op.create_foreign_key('room_ibfk_1', 'room', 'user', ['user_id'], ['id'])
    op.drop_table('association')
    # ### end Alembic commands ###
