"""modified Room user column

Revision ID: ee3dffe1625c
Revises: bab0d5b94c75
Create Date: 2020-11-08 20:03:09.983387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3dffe1625c'
down_revision = 'bab0d5b94c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
