"""add lazy attribute to user

Revision ID: fa7326ad7d69
Revises: 8cf0dfc962cf
Create Date: 2020-11-09 16:03:08.044310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7326ad7d69'
down_revision = '8cf0dfc962cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
